const mongoose = require('mongoose');

// Subdocument schema for deposits
const DepositSchema = new mongoose.Schema({
  amount: { type: Number, required: true },
  status: { type: String, enum: ["pending","approved"], default: "pending" },
  createdAt: { type: Date, default: Date.now }
  // _id is automatically generated by Mongoose
});

// Subdocument schema for withdrawals (optional if you need it)
const WithdrawalSchema = new mongoose.Schema({
  amount: { type: Number, required: true },
  status: { type: String, enum: ["pending","code_sent","approved"], default: "pending" },
  code: { type: String },       // for admin approval flow
  createdAt: { type: Date, default: Date.now }
});

const userSchema = new mongoose.Schema({
  fullName: { type: String, required: true },
  address: { type: String, required: true },
  phone: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  birthDate: { type: Date, required: true },
  password: { type: String, required: true },
  isVerified: { type: Boolean, default: false },
  balance: { type: Number, default: 0 },
  bonus: { type: Number, default: 0 },
  totalDeposit: { type: Number, default: 0 },
  totalWithdraw: { type: Number, default: 0 },
  verifyCode: { type: String },
  codeExpires: { type: Date },
  deposits: [{
  amount: { type: Number, required: true },
  method: { type: String },      // 🔹 Add payment method
  proof: { type: String },       // 🔹 Add proof (filename or URL)
  status: { type: String, enum: ["pending", "approved"], default: "pending" },
  createdAt: { type: Date, default: Date.now }
}],
  withdrawals: [WithdrawalSchema]  // optional, if you want to store them
}, { timestamps: true });

module.exports = mongoose.model('User', userSchema);